### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by dotsoftwarenl** [thebytelab/laravel-vapor-multi-region-deploy#2]
Hi!

We are looking for a package that can deploy multiple regions in 1 go. But I receive the following error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - thebytelab/vapor-multi-region-deploy[v1.0.0, ..., v1.0.2] require illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - thebytelab/vapor-multi-region-deploy[dev-master, v1.1.0] require illuminate/support ^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires thebytelab/vapor-multi-region-deploy * -> satisfiable by thebytelab/vapor-multi-region-deploy[dev-master, v1.0.0, v1.0.1, v1.0.2, v1.1.0, 9999999-dev].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require thebytelab/vapor-multi-region-deploy:*" to figure out if any version is installable, or "composer require thebytelab/vapor-multi-region-deploy:^2.1" if you know which you need.

Is this package still maintained/active?

**Comment by jkswoods** [comment]
Hey, yeah I'll pick this one up shortly.

**Comment by jkswoods** [comment]
Latest release (1.2.0) includes support for Laravel 10
